import type { QuickPlanInputs } from '@/lib/schemas/quick-plan-schema';

// Standard Demo Inputs
export const demoInputs1: QuickPlanInputs = {
  timeline: {
    id: 'demo-timeline1',
    name: 'Demo Timeline 1',
    lifeExpectancy: 82,
    currentAge: 31,
    retirementStrategy: { safeWithdrawalRate: 4, type: 'swrTarget' },
  },
  incomes: {
    'income-1': {
      id: 'income-1',
      name: 'software engineer salary',
      amount: 87500,
      frequency: 'yearly',
      timeframe: { start: { type: 'now' }, end: { type: 'atRetirement' } },
      growth: { growthRate: 3, growthLimit: 150000 },
    },
    'income-2': {
      id: 'income-2',
      name: 'freelance work',
      amount: 1000,
      frequency: 'monthly',
      timeframe: { start: { type: 'now' }, end: { type: 'atRetirement' } },
      growth: { growthRate: 2, growthLimit: 25000 },
    },
  },
  expenses: {
    'expense-1': {
      id: 'expense-1',
      name: 'living expenses',
      amount: 55000,
      frequency: 'yearly',
      timeframe: { start: { type: 'now' }, end: { type: 'atLifeExpectancy' } },
      growth: { growthRate: 3, growthLimit: 80000 },
    },
    'expense-2': {
      id: 'expense-2',
      name: 'vacations',
      amount: 5000,
      frequency: 'yearly',
      timeframe: { start: { type: 'now' }, end: { type: 'atLifeExpectancy' } },
      growth: { growthRate: 5, growthLimit: 12500 },
    },
  },
  accounts: {
    'account-1': {
      type: '401k',
      id: 'account-1',
      name: 'fidelity 401k',
      currentValue: 60000,
      percentBonds: 25,
    },
    'account-2': {
      type: 'rothIra',
      id: 'account-2',
      name: 'vanguard roth',
      currentValue: 30000,
      contributionBasis: 15000,
      percentBonds: 25,
    },
    'account-3': {
      type: 'taxableBrokerage',
      id: 'account-3',
      name: 'schwab brokerage',
      currentValue: 20000,
      costBasis: 12000,
      percentBonds: 10,
    },
    'account-4': {
      type: 'savings',
      id: 'account-4',
      name: 'emergency fund',
      currentValue: 10000,
    },
  },
  contributionRules: {
    'contribution-rule-1': {
      id: 'contribution-rule-1',
      accountId: 'account-1',
      rank: 1,
      contributionType: 'dollarAmount',
      dollarAmount: 11750,
      incomeIds: ['income-1'],
    },
    'contribution-rule-2': {
      id: 'contribution-rule-2',
      accountId: 'account-2',
      rank: 2,
      contributionType: 'dollarAmount',
      dollarAmount: 3500,
      incomeIds: ['income-1', 'income-2'],
    },
    'contribution-rule-3': {
      id: 'contribution-rule-3',
      accountId: 'account-3',
      rank: 3,
      contributionType: 'percentRemaining',
      percentRemaining: 60,
    },
    'contribution-rule-4': {
      id: 'contribution-rule-4',
      accountId: 'account-4',
      rank: 4,
      contributionType: 'unlimited',
      maxValue: 30000,
    },
  },
  baseContributionRule: { type: 'spend' },
  marketAssumptions: { stockReturn: 10, stockYield: 3.5, bondReturn: 5, bondYield: 4.5, cashReturn: 3, inflationRate: 3 },
};

// Early Retirement Demo Inputs
export const demoInputs2: QuickPlanInputs = {
  timeline: {
    id: 'demo-timeline2',
    name: 'Demo Timeline 2',
    lifeExpectancy: 87,
    currentAge: 28,
    retirementStrategy: { safeWithdrawalRate: 3.5, type: 'swrTarget' },
  },
  incomes: {
    'income-1': {
      id: 'income-1',
      name: 'tech salary',
      amount: 145000,
      frequency: 'yearly',
      timeframe: { start: { type: 'now' }, end: { type: 'atRetirement' } },
      growth: { growthRate: 4, growthLimit: 250000 },
    },
    'income-2': {
      id: 'income-2',
      name: 'RSU vesting',
      amount: 8750,
      frequency: 'quarterly',
      timeframe: { start: { type: 'now' }, end: { type: 'customAge', age: 35 } },
      growth: { growthRate: 10 },
    },
    'income-3': {
      id: 'income-3',
      name: 'side consulting',
      amount: 800,
      frequency: 'biweekly',
      timeframe: { start: { type: 'now' }, end: { type: 'atRetirement' } },
      growth: { growthRate: 3 },
    },
  },
  expenses: {
    'expense-1': {
      id: 'expense-1',
      name: 'frugal living expenses',
      amount: 35000,
      frequency: 'yearly',
      timeframe: { start: { type: 'now' }, end: { type: 'atLifeExpectancy' } },
      growth: { growthRate: 3, growthLimit: 50000 },
    },
    'expense-2': {
      id: 'expense-2',
      name: 'apartment rent',
      amount: 2000,
      frequency: 'monthly',
      timeframe: { start: { type: 'now' }, end: { type: 'customAge', age: 35 } },
      growth: { growthRate: 3 },
    },
    'expense-3': {
      id: 'expense-3',
      name: 'mortgage payment',
      amount: 2333,
      frequency: 'monthly',
      timeframe: { start: { type: 'customAge', age: 35 }, end: { type: 'customAge', age: 50 } },
    },
  },
  accounts: {
    'account-1': {
      type: '401k',
      id: 'account-1',
      name: 'fidelity 401k',
      currentValue: 85000,
      percentBonds: 10,
    },
    'account-2': {
      type: 'rothIra',
      id: 'account-2',
      name: 'vanguard roth',
      currentValue: 42000,
      contributionBasis: 30000,
      percentBonds: 10,
    },
    'account-3': {
      type: 'taxableBrokerage',
      id: 'account-3',
      name: 'schwab brokerage',
      currentValue: 120000,
      costBasis: 90000,
      percentBonds: 5,
    },
    'account-4': {
      type: 'hsa',
      id: 'account-4',
      name: 'fidelity hsa',
      currentValue: 15000,
      percentBonds: 10,
    },
  },
  contributionRules: {
    'contribution-rule-1': {
      id: 'contribution-rule-1',
      accountId: 'account-1',
      rank: 1,
      contributionType: 'unlimited',
      incomeIds: ['income-1', 'income-2'],
    },
    'contribution-rule-2': {
      id: 'contribution-rule-2',
      accountId: 'account-2',
      rank: 2,
      contributionType: 'unlimited',
      incomeIds: ['income-1', 'income-2', 'income-3'],
    },
    'contribution-rule-3': {
      id: 'contribution-rule-3',
      accountId: 'account-4',
      rank: 3,
      contributionType: 'unlimited',
    },
    'contribution-rule-4': {
      id: 'contribution-rule-4',
      accountId: 'account-3',
      rank: 4,
      contributionType: 'percentRemaining',
      percentRemaining: 85,
    },
  },
  baseContributionRule: { type: 'save' },
  marketAssumptions: { stockReturn: 9, stockYield: 2, bondReturn: 4, bondYield: 3.5, cashReturn: 3, inflationRate: 3 },
};

// Career Transition Demo Inputs
export const demoInputs3: QuickPlanInputs = {
  timeline: {
    id: 'demo-timeline3',
    name: 'Demo Timeline 3',
    lifeExpectancy: 77,
    currentAge: 38,
    retirementStrategy: { safeWithdrawalRate: 4, type: 'swrTarget' },
  },
  incomes: {
    'income-1': {
      id: 'income-1',
      name: 'marketing job',
      amount: 75000,
      frequency: 'yearly',
      timeframe: { start: { type: 'now' }, end: { type: 'customDate', month: 6, year: 2026 } },
    },
    'income-2': {
      id: 'income-2',
      name: 'severance package',
      amount: 25000,
      frequency: 'oneTime',
      timeframe: { start: { type: 'customDate', month: 6, year: 2026 } },
    },
    'income-3': {
      id: 'income-3',
      name: 'part-time work',
      amount: 15000,
      frequency: 'yearly',
      timeframe: { start: { type: 'customDate', month: 7, year: 2026 }, end: { type: 'customDate', month: 6, year: 2027 } },
    },
    'income-4': {
      id: 'income-4',
      name: 'UX designer salary',
      amount: 65000,
      frequency: 'yearly',
      timeframe: { start: { type: 'customDate', month: 7, year: 2027 }, end: { type: 'atRetirement' } },
      growth: { growthRate: 4, growthLimit: 120000 },
    },
    'income-5': {
      id: 'income-5',
      name: 'spouse income',
      amount: 55000,
      frequency: 'yearly',
      timeframe: { start: { type: 'now' }, end: { type: 'atRetirement' } },
      growth: { growthRate: 3, growthLimit: 80000 },
    },
  },
  expenses: {
    'expense-1': {
      id: 'expense-1',
      name: 'household expenses',
      amount: 65000,
      frequency: 'yearly',
      timeframe: { start: { type: 'now' }, end: { type: 'atLifeExpectancy' } },
      growth: { growthRate: 3 },
    },
    'expense-2': {
      id: 'expense-2',
      name: 'bootcamp tuition',
      amount: 18000,
      frequency: 'oneTime',
      timeframe: { start: { type: 'customDate', month: 7, year: 2026 } },
    },
    'expense-3': {
      id: 'expense-3',
      name: 'certification & tools',
      amount: 3000,
      frequency: 'oneTime',
      timeframe: { start: { type: 'customDate', month: 1, year: 2027 } },
    },
    'expense-4': {
      id: 'expense-4',
      name: 'child daycare',
      amount: 15000,
      frequency: 'yearly',
      timeframe: { start: { type: 'now' }, end: { type: 'customAge', age: 50 } },
    },
  },
  accounts: {
    'account-1': {
      type: '401k',
      id: 'account-1',
      name: 'marketing 401k',
      currentValue: 125000,
      percentBonds: 30,
    },
    'account-2': {
      type: 'ira',
      id: 'account-2',
      name: 'rollover ira',
      currentValue: 45000,
      percentBonds: 30,
    },
    'account-3': {
      type: 'rothIra',
      id: 'account-3',
      name: 'spouse roth',
      currentValue: 22000,
      contributionBasis: 15000,
      percentBonds: 25,
    },
    'account-4': {
      type: 'taxableBrokerage',
      id: 'account-4',
      name: 'joint brokerage',
      currentValue: 35000,
      costBasis: 28000,
      percentBonds: 20,
    },
    'account-5': {
      type: 'savings',
      id: 'account-5',
      name: 'transition fund',
      currentValue: 40000,
    },
  },
  contributionRules: {
    'contribution-rule-1': {
      id: 'contribution-rule-1',
      accountId: 'account-1',
      rank: 1,
      contributionType: 'dollarAmount',
      dollarAmount: 5000,
      incomeIds: ['income-1'],
    },
    'contribution-rule-2': {
      id: 'contribution-rule-2',
      accountId: 'account-3',
      rank: 2,
      contributionType: 'unlimited',
      incomeIds: ['income-5'],
    },
    'contribution-rule-3': {
      id: 'contribution-rule-3',
      accountId: 'account-5',
      rank: 3,
      contributionType: 'unlimited',
      maxValue: 50000,
    },
    'contribution-rule-4': {
      id: 'contribution-rule-4',
      accountId: 'account-4',
      rank: 4,
      contributionType: 'percentRemaining',
      percentRemaining: 30,
    },
  },
  baseContributionRule: { type: 'save' },
  marketAssumptions: { stockReturn: 9, stockYield: 2.5, bondReturn: 4.5, bondYield: 4, cashReturn: 3, inflationRate: 3 },
};
